import './globals.css';

export const metadata = {
  title: 'VALORANT - Kobra Labs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-BR'>
      <head>
        <meta
          name='google-site-verification'
          content='lAFJGF0yUXC3X6sbYqKTE2fHWavIMSgZSe8oebXuLNU'
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
