import './globals.css';

export const metadata = {
  title: 'VALORANT - Kobra Labs',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='pt-BR'>
      <body>{children}</body>
    </html>
  );
}
